version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - python -m pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  build:
    commands:
      - echo Running tests...
      - python -m pytest tests/ || true   # run tests but don’t fail build for demo
      # - python app.py   # remove this in build, run in deploy instead
artifacts:
  files:
    - '**/*'
