name: Deploy Lambda

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # =========================
    # 1. Checkout code
    # =========================
    - name: Checkout repo
      uses: actions/checkout@v3

    # =========================
    # 2. Zip Lambda code
    # =========================
    - name: Zip Lambda
      run: |
        cd functions
        zip -r ../function.zip .

    # =========================
    # 3. AWS login
    # =========================
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # =========================
    # 4. Upload zip to S3
    # =========================
    - name: Upload to S3
      run: |
        aws s3 cp function.zip s3://my-lambda-code-bucket-12345/function.zip

    # =========================
    # 5. Deploy Lambda
    # =========================
    - name: Update Lambda
      run: |
        aws lambda update-function-code \
          --function-name MoveFileLambda \
          --s3-bucket my-lambda-code-bucket-12345 \
          --s3-key function.zip